{% set name = "ramscube" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mheikenfeld/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 888a2e1f26eb4321e240b7f3da5820f4c352f422d5397c7105dd9ad4a0096640

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - iris
    - xarray
    - cf_units

test:
  imports:
    - ramscube
  source_files:
    - ramscube/tests/test_dummy.py
  requires:
    - pytest
  commands:
    - pytest ramscube/tests
about:
  home: http://github.com/mheikenfeld/ramscube
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Load data from RAMS output files (hdf5) to iris cubes

  description: Load data from RAMS output files (hdf5) to iris cubes
  doc_url: http://ramscube.readthedocs.io/
  dev_url: https://github.com/mheikenfeld/ramscube

extra:
  recipe-maintainers:
    - mheikenfeld
